### ISSUE TITLE
Flag to disable "undefined key" warning

### ISSUE THREAD

**Issue by mkurz** [djspiewak/sbt-github-packages#10]
First: Thanks a lot for this plugin @djspiewak!

I do have a very small request: Would it be possible to disable the warning if `githubOwner` and `githubRepository` isn't set?

https://github.com/djspiewak/sbt-github-packages/blob/8f2a34883e33fc6d63aa7e9b8198e1f00b869258/src/main/scala/sbtghpackages/GitHubPackagesPlugin.scala#L67-L68

I do get your point why you print this warning, and of course it can stay the default, however if I use the plugin solely to retrieve packages from private repositories (which are libraries for our main project), we do not want to publish to this repositories from within our main project. Setting github-actor and token is enough for such a case. Therefore this warning is very annoying and also can cause problems in CI/CD pipelines.

I am not 100% sure how such a flag should be called. Maybe it should not be about the warning, but more about the purpose how the plugin is used. E.g. `notPublishing := true`, `fetchOnly := true`, `readOnly := true`, `publishing := false` (which is `true` by default), `repoOnly := true` or something like that.

What do you think?

**Comment by djspiewak** [comment]
I'm completely okay with suppressing the warning. I'd say something like `githubSuppressPublicationWarning := true` or something like that. WDYT?

**Comment by mkurz** [comment]
Sound great too me! Thanks!

**Comment by mkurz** [comment]
Any chance we see this in the next release? Thanks!

**Comment by djspiewak** [comment]
Definitely if I can get to it! Sorry been really swamped. It's not a hard thing to do, just… time. :-( I'll make an 0.4.2 for it though if I can get it done soon.

**Comment by djspiewak** [comment]
Okay actually this was really easy. Done and released.

**Comment by mkurz** [comment]
Nice, thanks a lot!
