### ISSUE TITLE
Scala 2.11 package compatibility

### ISSUE THREAD

**Issue by peterdeka** [djspiewak/sbt-github-packages#14]
Hi we really appreciate your plugin, in the last days some published packages in this repo disappeared (2.11 versions mainly), are you planning on releasing for 2.11?

Thanks,
Pietro

**Comment by djspiewak** [comment]
I'm not sure what you mean, exactly? Sbt >=1.0 is based on Scala 2.12, so there can be no 2.11 release. Did you mean that you attempted to use this plugin to release your own package cross-build for 2.11 and it didn't work?

**Comment by lightsaway** [comment]
@djspiewak what about 2.13? Are you planning to release this plugin for scala 2.13?

**Comment by djspiewak** [comment]
> what about 2.13? Are you planning to release this plugin for scala 2.13?

Same as 2.11: sbt uses Scala 2.12, not 2.11 or 2.13. Thus, this plugin *itself* will only ever be published for 2.12. However, you can use it to publish projects on 2.11, 2.12, 2.13, 3.0 (when it arrives), and really anything else.

**Comment by lightsaway** [comment]
@djspiewak just to be sure i was doing proper things:

- I have sbt project with sbt 1.3.8 and scala 2.13.1
- added **addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.4.0")** 

Running sbt update gives me following error:
 ```sbt.librarymanagement.ResolveException: Error downloading com.codecommit:sbt-github-packages;sbtVersion=1.0;scalaVersion=2.13:0.4.0```
Shouldn't the plugin be republished with compilation under 2.13.1 compiler??

**Comment by mkurz** [comment]
@lightsaway Where did you define Scala 2.13.1. In `build.sbt`?

**Comment by mkurz** [comment]
You have to put 
```
scalaVersion := "2.13.1"
```
in `build.sbt`
and 
```
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.4.2")
```
in `project/plugins.sbt`

**Comment by lightsaway** [comment]
@mkurz thanks for the help. I got a bit more complex problem multimodule build that had  autoplugin that used this plugin as dependency. It appeared that i need to explicitly set scalaVersion to 2.12 in that module that was building the plugin, besides the fact that other modules were using 2.13.
