### ISSUE TITLE
Cross publishing to GitHub Packages and Sonatype

### ISSUE THREAD

**Issue by xerial** [djspiewak/sbt-github-packages#15]
Hi. Thanks for the wonderful plugin. I could publish my project to GitHub packages! 

A problem, however, is `publishTo` setting, which always points to GitHub Packages repository:
https://github.com/djspiewak/sbt-github-packages/blob/d3ed869bcc10e26b37e04312f6218d187ab7d79b/src/main/scala/sbtghpackages/GitHubPackagesPlugin.scala#L58-L59

So switching the target repository between GitHub packages and Sonatype is not straightforward.

How about adding a separate settingKey like `githubPublishTo` so that we can switch `publishTo` setting to `githubPublishTo` or `sonatypePublishToBundle` at ease? 

With this change, we may need to ask users to add this setting: 
```scala
publishTo := githubPublishTo
```

What do you think? 

- version: 0.5.0

**Comment by djspiewak** [comment]
I think this is a good idea! It makes the plugin more composable, basically. Not at all difficult to achieve; just a bit of refactoring. I think the default behavior will remain what it is today (where the `publishTo` is overridden by default), but having the setting be a separate thing means that users can control it on their own if they want to override it back.

**Comment by xerial** [comment]
Good to hear that. I’ll create a PR later. Thanks.
