### ISSUE TITLE
Group and artifact IDs seem to be wrong

### ISSUE THREAD

**Issue by keyvan** [djspiewak/sbt-github-packages#6]
After publishing the artifacts to GitHub Packages from my repository, I think the values assigned for artifactId and groupId are both wrong. I played around with my SBT settings thinking that perhaps something's wrong there but everything seems to be the way they should be. Then I went to the packages published on this repo and noticed that the packages here have the exact same pattern that doesn't seem to be correct:

```
<dependency>
  <groupId>com.codecommit.sbt-github-packages-tests-publish_2</groupId>
  <artifactId>12</artifactId>
  <version>0.2.1</version>
</dependency>
```

I would expect this to be something like:

```
<dependency>
  <groupId>com.codecommit</groupId>
  <artifactId>sbt-github-packages-tests-publish_2.12</artifactId>
  <version>0.2.1</version>
</dependency>
```

Am I missing something?

**Comment by djspiewak** [comment]
It's a bug in the github web UI. If you use the expected artifact ids, they will work just fine! The web UI is just rendering things incorrectly.

**Comment by keyvan** [comment]
Ah, good to know. Thanks for sharing.
