### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by tinydylan** [djspiewak/sbt-github-packages#7]
> Note that you probably shouldn't use this with plugins, only libraries. 

Just wondering why this is so. I'd really like to publish a plugin I use for common sbt settings.

**Comment by djspiewak** [comment]
Sbt plugins leverage Ivy-specific repository layouts in default configuration. You *can* publish them to Maven repositories and it does work, but the edge cases you hit can sometimes be a little strange. Nearly all current sbt plugins are hosted on Bintray in Ivy (not Maven) repositories.

Anyway, given the way that GitHub Packages seems to be somewhat sensitive to what files *exactly* make up an artifact, I wouldn't necessarily trust it to not mess up plugin data. However, if you'd like to give it a try, I'd be very interested in the experimental results!

**Comment by tinydylan** [comment]
It seems to work fine for our simple plugin. I've also tested on a maven repo on cloudsmith.io - works fine, too. Maybe our plugin is just simple enough to get away with it. Dunno.

**Comment by djspiewak** [comment]
@tinydylan Good to know! I'll remove the warning for now and we'll see if people complain. I'm guessing that I was just being overly-pessimistic and your results are representative.

**Comment by tinydylan** [comment]
Let's hope so :)
