### ISSUE TITLE
Loading plugin for v0.3.0 results in sbt error

### ISSUE THREAD

**Issue by melton1968** [djspiewak/sbt-github-packages#8]
Adding the following to plugins.sbt:

    addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.3.0")

produces this error:

```
[info] Loading global plugins from /Users/mmelton/.sbt/1.0/plugins
[info] Loading settings for project scala-time-build from plugins.sbt,idea776.sbt ...
[info] Loading project definition from /Users/mmelton/work/scala-time/project
[info] Loading settings for project scala-time from build.sbt ...
[error] Reference to undefined setting: 
[error] 
[error]   githubActor from credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
[error]  
[error] Use 'last' for the full log.
```

Version 0.2.1 loads without complaint.

**Comment by djspiewak** [comment]
We broke compatibility between the versions so as to adjust the default configuration to something more in alignment with GitHub Actions. To that end, rather than reading github.user out of the git config, we read github.actor. Renaming the keys should make your build run again.
